# Dockerfile
FROM nginx:alpine

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built web export (already generated by `expo export --platform web`)
COPY dist /usr/share/nginx/html

# (Optional) Drop an extra security header layer
# RUN apk add --no-cache bash

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]